#ifndef _EVT_H_
#define _EVT_H_

#include <stdint.h>
#include "ultra64.h"

// PC scripts must be able to store host pointers directly in bytecode arrays.
typedef intptr_t Bytecode;

enum {
    EVT_OP_INTERNAL_FETCH,
    EVT_OP_END,
    EVT_OP_RETURN,
    EVT_OP_LABEL,
    EVT_OP_GOTO,
    EVT_OP_LOOP,
    EVT_OP_END_LOOP,
    EVT_OP_BREAK_LOOP,
    EVT_OP_WAIT_FRAMES,
    EVT_OP_WAIT_SECS,
    EVT_OP_IF_EQ,
    EVT_OP_IF_NE,
    EVT_OP_IF_LT,
    EVT_OP_IF_GT,
    EVT_OP_IF_LE,
    EVT_OP_IF_GE,
    EVT_OP_IF_FLAG,
    EVT_OP_IF_NOT_FLAG,
    EVT_OP_ELSE,
    EVT_OP_END_IF,
    EVT_OP_SWITCH,
    EVT_OP_SWITCH_CONST,
    EVT_OP_CASE_EQ,
    EVT_OP_CASE_NE,
    EVT_OP_CASE_LT,
    EVT_OP_CASE_GT,
    EVT_OP_CASE_LE,
    EVT_OP_CASE_GE,
    EVT_OP_CASE_DEFAULT,
    EVT_OP_CASE_OR_EQ,
    EVT_OP_CASE_AND_EQ,
    EVT_OP_CASE_FLAG,
    EVT_OP_END_CASE_GROUP,
    EVT_OP_CASE_RANGE,
    EVT_OP_BREAK_SWITCH,
    EVT_OP_END_SWITCH,
    EVT_OP_SET,
    EVT_OP_SET_CONST,
    EVT_OP_SETF,
    EVT_OP_ADD,
    EVT_OP_SUB,
    EVT_OP_MUL,
    EVT_OP_DIV,
    EVT_OP_MOD,
    EVT_OP_ADDF,
    EVT_OP_SUBF,
    EVT_OP_MULF,
    EVT_OP_DIVF,
    EVT_OP_USE_BUF,
    EVT_OP_BUF_READ1,
    EVT_OP_BUF_READ2,
    EVT_OP_BUF_READ3,
    EVT_OP_BUF_READ4,
    EVT_OP_BUF_PEEK,
    EVT_OP_USE_FBUF,
    EVT_OP_FBUF_READ1,
    EVT_OP_FBUF_READ2,
    EVT_OP_FBUF_READ3,
    EVT_OP_FBUF_READ4,
    EVT_OP_FBUF_PEEK,
    EVT_OP_USE_ARRAY,
    EVT_OP_USE_FLAGS,
    EVT_OP_MALLOC_ARRAY,
    EVT_OP_BITWISE_AND,
    EVT_OP_BITWISE_AND_CONST,
    EVT_OP_BITWISE_OR,
    EVT_OP_BITWISE_OR_CONST,
    EVT_OP_CALL,
    EVT_OP_EXEC,
    EVT_OP_EXEC_GET_TID,
    EVT_OP_EXEC_WAIT,
    EVT_OP_BIND_TRIGGER,
    EVT_OP_UNBIND,
    EVT_OP_KILL_THREAD,
    EVT_OP_JUMP,
    EVT_OP_SET_PRIORITY,
    EVT_OP_SET_TIMESCALE,
    EVT_OP_SET_GROUP,
    EVT_OP_BIND_PADLOCK,
    EVT_OP_SUSPEND_GROUP,
    EVT_OP_RESUME_GROUP,
    EVT_OP_SUSPEND_OTHERS,
    EVT_OP_RESUME_OTHERS,
    EVT_OP_SUSPEND_THREAD,
    EVT_OP_RESUME_THREAD,
    EVT_OP_IS_THREAD_RUNNING,
    EVT_OP_THREAD,
    EVT_OP_END_THREAD,
    EVT_OP_CHILD_THREAD,
    EVT_OP_END_CHILD_THREAD,
    EVT_OP_DEBUG_LOG,
    EVT_OP_DEBUG_PRINT_VAR,
    EVT_OP_92,
    EVT_OP_93,
    EVT_OP_94,
};

#define MAKE_ENTITY_END      0x80000000

#define EVT_CONTINUE 0
#define EVT_ABORT    1
#define EVT_FINISH   255

typedef s32 ApiStatus;
#define ApiStatus_BLOCK  0
#define ApiStatus_DONE1  1
#define ApiStatus_DONE2  2
#define ApiStatus_REPEAT 3
#define ApiStatus_FINISH 255

enum EventCommandResults {
    EVT_CMD_RESULT_YIELD        = -1,
    EVT_CMD_RESULT_CONTINUE     = 0,
    EVT_CMD_RESULT_ERROR        = 1,
};

enum EventGroupFlags {
    EVT_GROUP_FLAG_INTERACT = 0x01,
    EVT_GROUP_FLAG_MENUS    = 0x02,
    EVT_GROUP_FLAG_CAM      = 0x04,
    EVT_GROUP_FLAG_UNUSED   = 0x08,
    EVT_GROUP_FLAG_BATTLE   = 0x10,

    EVT_GROUP_NEVER_PAUSE   = 0x00,
    EVT_GROUP_PASSIVE_NPC   = EVT_GROUP_FLAG_MENUS | EVT_GROUP_FLAG_UNUSED,
    EVT_GROUP_HOSTILE_NPC   = EVT_GROUP_FLAG_INTERACT | EVT_GROUP_FLAG_MENUS | EVT_GROUP_FLAG_UNUSED,
    EVT_GROUP_EXIT_MAP      = EVT_GROUP_FLAG_INTERACT | EVT_GROUP_FLAG_MENUS | EVT_GROUP_FLAG_UNUSED | EVT_GROUP_FLAG_BATTLE,
    EVT_GROUP_SHAKE_CAM     = EVT_GROUP_FLAG_CAM,
    EVT_GROUP_NOT_BATTLE    = 0xFF & ~EVT_GROUP_FLAG_BATTLE,
};

enum EventPriority {
    EVT_PRIORITY_0          = 0x00,
    EVT_PRIORITY_1          = 0x01,
    EVT_PRIORITY_A          = 0x0A,
    EVT_PRIORITY_14         = 0x14,
};

enum EventStateFlags {
    EVT_FLAG_ACTIVE             = 0x01,
    EVT_FLAG_PAUSED             = 0x02,
    EVT_FLAG_BLOCKED_BY_CHILD   = 0x10,
    EVT_FLAG_RUN_IMMEDIATELY    = 0x20,
    EVT_FLAG_THREAD             = 0x40,
    EVT_FLAG_SUSPENDED          = 0x80,
};

#endif
